### ISSUE TITLE
AMP Review 1

### ISSUE THREAD

**Issue by melaniebeck** [fastforwardlabs/mlflow_tracking#2]
- [x] As Andrew pointed out to me, these should all probably say 2021, not 2020 :( https://github.com/fastforwardlabs/mlflow_tracking/blob/445dc5577fa2291d9aae51de964602d4f5476b6e/cml/install_dependencies.py#L4
- [x] Andrew also told me about a new requirement posed by Alex B. to include specific instructions in the README for the many ways to deploy on CML. He suggested something like this: 

## Deploying on CML
There are three ways to launch this project on CML:
1.  **From Prototype Catalog** - Navigate to the Prototype Catalog on a CML workspace, select the "Deep Learning for Question Answering" tile, click "Launch as Project", click "Configure Project"
2. **As ML Prototype** - In a CML workspace, click "New Project", add a Project Name, select "ML Prototype" as the Initial Setup option, copy in the [repo URL](https://github.com/fastforwardlabs/mlflow_tracking), click "Create Project", click "Configure Project"
3.  **Manual Setup** - In a CML workspace, click "New Project", add a Project Name, select "Git" as the Initial Setup option, copy in the [repo URL](https://github.com/fastforwardlabs/mlflow_tracking), click "Create Project". Launch a Python3 Workbench Session with at least 2GB of memory and 1vCPUs. Then follow these instructions below, in order.

- [x] Add a thumbnail image for the Prototype Catalog
- [x] In the manual setup portion of the README, could you add instructions for setting the default python path in order for the training scripts to run properly in a CML session? That threw me off when running through manual setup but I remembered seeing it in the .yaml file. 

After thinking about it more, perhaps you intended for users to `cd` into the scripts directory to run them? And that's why you didn't specify the directory in the cmd line call? i.e. , 
```bash
!python3 train_kneighbors.py --n-neighbors 3
```
 instead of 
```bash
!python3 scripts/train_kneighbors.py --n-neighbors 3
```

Either way is probably fine but if it's the latter, then a note to tell users to `cd` into the scripts directory before running the calls might be helpful.

**Comment by cjwallace** [comment]
Good points all! I submitted PR #3 to address them, and request your review. For the scripts directory, I intended everything to be run from the top-level directory, so I've fixed the instructions to include it (great catch!).

**Comment by melaniebeck** [comment]
The PR looks great!  I went ahead and merged it. 

But I did find a couple of stragglers: the `.py` files in the `cml` directory still have 2020 in the header. Since there are only two, I can go ahead and update that real quick-like.
